{{/*
=============================================================================
Plataforma E - ServiceAccount
=============================================================================
*/}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fabrica-agentes.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fabrica-agentes.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
